name: Sync-to-Staging

on:
  push:
    branches:
      - staging

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev Repository
        uses: actions/checkout@v3
        with:
          ref: staging

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_PRIVKEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Sync to staging
        run: |
          git config --global user.name "SIGMPS Admin"
          git config --global user.email "sigmps-admin@ipsj.or.jp"
          git remote add staging git@github.com:sigmps/staging.sigmps.github.io.git
      - name: fetch staging
        run: |
          git fetch staging
          git checkout -b master --track staging/master
      - name: merge
        run: |
          git merge --allow-unrelated-histories --no-ff production -m "Sync page contents from a develop repo"
      - name: push
        run: |
          GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push -f staging master
